### Data Cleaning using numpy

#### The following are the student marks of a class

[44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,,122,92,np.nan,87,96,97,1,19,2,53, 44]

In [100]:
import numpy as np

In [101]:
marks = np.array([44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,122,92,np.nan,87,96,97,1,19,2,53, 44])
marks

array([ 44.,  24.,  nan,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  nan,  nan,   3.,  56.,  81.,  59., 122.,  92.,  nan,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  44.])

In [102]:
np.isnan(marks)

array([False, False,  True, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False])

#### 1.Find the no of outliers and missing values?

In [103]:
len(marks[np.isnan(marks)])  # missing values

4

In [104]:
cond = (marks>100) | (marks < 0) # outliers
condi

array([False, False, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False])

In [105]:
len(marks[cond])  

3

#### 2.replace the outliers with 45 and missing value with 87.

In [112]:
m = np.array([np.where(np.isnan(marks),87,marks)],dtype = "int16") # missing value
m

array([[ 44,  24,  87,  59,  32,  96, 188,  52,  62,  58,  52, 120,  87,
         87,   3,  56,  81,  59, 122,  92,  87,  87,  96,  97,   1,  19,
          2,  53,  44]], dtype=int16)

In [113]:
marks1 = np.where(cond,45,m)
marks1

array([[44, 24, 87, 59, 32, 96, 45, 52, 62, 58, 52, 45, 87, 87,  3, 56,
        81, 59, 45, 92, 87, 87, 96, 97,  1, 19,  2, 53, 44]], dtype=int16)

#### 3.what is the average marks of students after 2nd step?

In [114]:
np.mean(marks1)

56.96551724137931

#### 4.How many students got less than 60 marks?.

In [116]:
len(marks1[marks1 < 60])

18

#### 5.what is the maximum marks?

In [118]:
np.max(marks1)

97

#### 6.Convert the marks to float32.

In [119]:
np.array(marks1,dtype = "float64")

array([[44., 24., 87., 59., 32., 96., 45., 52., 62., 58., 52., 45., 87.,
        87.,  3., 56., 81., 59., 45., 92., 87., 87., 96., 97.,  1., 19.,
         2., 53., 44.]])

### Solving Linear Equations

In [13]:
a = np.array([[2,3,-1],[1,-1,2],[3,2,1]])
a

array([[ 2,  3, -1],
       [ 1, -1,  2],
       [ 3,  2,  1]])

In [14]:
b = np.array([10,5,12])
b

array([10,  5, 12])

In [15]:
np.linalg.solve(a,b)

array([-7.36952666e+15,  7.36952666e+15,  7.36952666e+15])

In [17]:
a = np.array([[2,1,-1,3],[3,-2,2,2],[1,3,-2,1],[4,-1,1,-2]])
a

array([[ 2,  1, -1,  3],
       [ 3, -2,  2,  2],
       [ 1,  3, -2,  1],
       [ 4, -1,  1, -2]])

In [19]:
b = np.array([8,1,7,3])
b

array([8, 1, 7, 3])

In [20]:
np.linalg.solve(a,b)

array([ 1.73170732, -0.75609756, -3.46341463,  0.6097561 ])

In [22]:
a = np.array([[4,2,-3],[-2,3,1],[1,-1,2]])
a

array([[ 4,  2, -3],
       [-2,  3,  1],
       [ 1, -1,  2]])

In [24]:
b = np.array([10,-3,4])
b

array([10, -3,  4])

In [25]:
np.linalg.solve(a,b)

array([2.85365854, 0.6097561 , 0.87804878])

### Conditional Selection with np.where()

#### 1.Generate a random 1D array A of 10 integers between 1 and 100.

In [30]:
arr1 = np.random.randint(1,100,10)
A = np.array(arr1)
A

array([35, 95, 31, 93, 80, 65, 56, 35, 92, 52])

#### 2.Use np.where() to find the indices where the elements of A are greater than 50.

In [38]:
cond = A>50
print(A[cond])
np.where(cond)

[95 93 80 65 56 92 52]


(array([1, 3, 4, 5, 6, 8, 9], dtype=int64),)

#### 3.Create a new array B that contains elements from A where the condition is met.

In [45]:
B = np.array(A[A>50])
B

array([95, 93, 80, 65, 56, 92, 52])

#### 4.Calculate the mean of array B and print it along with arrays A and B.

In [46]:
np.mean(B)  # mean

76.14285714285714

In [47]:
np.mean(A)  # mean

63.4

### Replace Values with np.where()

#### 1.Create a 4x4 random integer matrix C with values between -10 and 10

In [52]:
c = np.random.randint(-10,10,16).reshape(4,4)
c

array([[  5, -10,   1,   1],
       [  6,   6,   9,  -5],
       [  5, -10,   5,  -9],
       [  2,  -1,   0,   4]])

#### 2.Use np.where() to replace all negative values in matrix C with 0

In [56]:
modified = np.where(c < 0,0,c)
modified

array([[5, 0, 1, 1],
       [6, 6, 9, 0],
       [5, 0, 5, 0],
       [2, 0, 0, 4]])

#### 3.Print the original matrix C and the modified matrix.

In [55]:
c

array([[  5, -10,   1,   1],
       [  6,   6,   9,  -5],
       [  5, -10,   5,  -9],
       [  2,  -1,   0,   4]])

In [57]:
modified

array([[5, 0, 1, 1],
       [6, 6, 9, 0],
       [5, 0, 5, 0],
       [2, 0, 0, 4]])