In [347]:
import numpy as np

### 1.clean the data(outlier,missing values,type conversion)

### sepal width

In [519]:
Iris = np.genfromtxt(r"C:\Users\LENOVO\Downloads\Iris_clean_-_Copy.csv",dtype = "float64",delimiter = ",")
Iris

array([[      nan,       nan,       nan,       nan],
       [5.100e+00, 3.500e+00, 1.400e+00, 2.000e-01],
       [4.900e+00, 3.000e+00, 1.400e+00, 2.000e-01],
       [4.700e+00, 3.200e+00, 1.300e+00, 2.000e-01],
       [4.600e+00, 3.100e+00, 1.500e+00, 1.020e+01],
       [5.000e+01, 3.600e+00, 1.400e+00, 2.000e-01],
       [5.400e+00,       nan, 1.700e+00, 4.000e-01],
       [4.600e+00, 3.400e+00, 1.400e+00, 3.000e-01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01],
       [4.400e+00, 2.900e+00, 1.400e+00, 2.000e-01],
       [4.900e+00, 3.100e+00,       nan, 1.000e-01],
       [5.400e+00, 3.700e+00, 1.500e+00, 2.000e-01],
       [4.800e+00, 3.400e+00, 1.600e+00, 2.000e-01],
       [4.800e+00, 1.300e+02, 1.400e+00, 1.010e+01],
       [4.300e+00, 3.000e+00, 1.100e+00, 1.000e-01],
       [5.800e+00, 4.000e+00, 1.200e+00, 2.000e-01],
       [5.700e+00, 4.400e+00, 1.500e+00, 4.000e-01],
       [5.040e+01,       nan, 1.300e+00, 4.000e-01],
       [5.100e+00, 3.500e+00, 1.400e+00, 3.000

In [480]:
width = Iris[1:,1]
width

array([  3.5,   3. ,   3.2,   3.1,   3.6,   nan,   3.4,   3.4,   2.9,
         3.1,   3.7,   3.4, 130. ,   3. ,   4. ,   4.4,   nan,   3.5,
         3.8,   3.8,   3.4,   3.7,   3.6,   3.3,   3.4,   3. ,  34. ,
         3.5,   3.4,   3.2,   3.1,   3.4,   4.1,   4.2,   3.1,   3.2,
         3.5,   3.1,   3. ,   3.4,   3.5,   2.3,   3.2,   3.5,   3.8,
         3. ,   3.8,   3.2,   3.7,   3.3,   3.2,   3.2,   nan,   2.3,
         2.8,   2.8,   3.3,   2.4,   2.9,   2.7,   2. ,   3. ,   2.2,
         2.9,   2.9,   3.1,   3. ,   2.7,   2.2,   2.5,   3.2,   2.8,
         2.5,   nan,   2.9,   3. ,   2.8,   3. ,   2.9,   2.6,   2.4,
         2.4,   2.7,   2.7,   3. ,   3.4,   3.1,   2.3,   3. ,   2.5,
         2.6,   3. , 112.6,   2.3,   2.7,   3. ,   2.9,   2.9,   2.5,
         2.8,   3.3,   2.7,   3. ,   2.9,   3. ,   3. ,   2.5,   2.9,
         2.5,   3.6,   3.2,   2.7,   3. ,   2.5,   2.8,   3.2,   3. ,
         3.8,   2.6,   2.2,   3.2,   2.8,   2.8,   2.7,   3.3,   3.2,
         2.8,   3. ,

In [481]:
Iris = np.where(width == -1,np.nan,width) #nan values
Iris

array([  3.5,   3. ,   3.2,   3.1,   3.6,   nan,   3.4,   3.4,   2.9,
         3.1,   3.7,   3.4, 130. ,   3. ,   4. ,   4.4,   nan,   3.5,
         3.8,   3.8,   3.4,   3.7,   3.6,   3.3,   3.4,   3. ,  34. ,
         3.5,   3.4,   3.2,   3.1,   3.4,   4.1,   4.2,   3.1,   3.2,
         3.5,   3.1,   3. ,   3.4,   3.5,   2.3,   3.2,   3.5,   3.8,
         3. ,   3.8,   3.2,   3.7,   3.3,   3.2,   3.2,   nan,   2.3,
         2.8,   2.8,   3.3,   2.4,   2.9,   2.7,   2. ,   3. ,   2.2,
         2.9,   2.9,   3.1,   3. ,   2.7,   2.2,   2.5,   3.2,   2.8,
         2.5,   nan,   2.9,   3. ,   2.8,   3. ,   2.9,   2.6,   2.4,
         2.4,   2.7,   2.7,   3. ,   3.4,   3.1,   2.3,   3. ,   2.5,
         2.6,   3. , 112.6,   2.3,   2.7,   3. ,   2.9,   2.9,   2.5,
         2.8,   3.3,   2.7,   3. ,   2.9,   3. ,   3. ,   2.5,   2.9,
         2.5,   3.6,   3.2,   2.7,   3. ,   2.5,   2.8,   3.2,   3. ,
         3.8,   2.6,   2.2,   3.2,   2.8,   2.8,   2.7,   3.3,   3.2,
         2.8,   3. ,

In [482]:
np.nanmedian(width)

3.0

In [483]:
Iris = np.where(np.isnan(width),np.nanmedian(width),width)
Iris

array([  3.5,   3. ,   3.2,   3.1,   3.6,   3. ,   3.4,   3.4,   2.9,
         3.1,   3.7,   3.4, 130. ,   3. ,   4. ,   4.4,   3. ,   3.5,
         3.8,   3.8,   3.4,   3.7,   3.6,   3.3,   3.4,   3. ,  34. ,
         3.5,   3.4,   3.2,   3.1,   3.4,   4.1,   4.2,   3.1,   3.2,
         3.5,   3.1,   3. ,   3.4,   3.5,   2.3,   3.2,   3.5,   3.8,
         3. ,   3.8,   3.2,   3.7,   3.3,   3.2,   3.2,   3. ,   2.3,
         2.8,   2.8,   3.3,   2.4,   2.9,   2.7,   2. ,   3. ,   2.2,
         2.9,   2.9,   3.1,   3. ,   2.7,   2.2,   2.5,   3.2,   2.8,
         2.5,   3. ,   2.9,   3. ,   2.8,   3. ,   2.9,   2.6,   2.4,
         2.4,   2.7,   2.7,   3. ,   3.4,   3.1,   2.3,   3. ,   2.5,
         2.6,   3. , 112.6,   2.3,   2.7,   3. ,   2.9,   2.9,   2.5,
         2.8,   3.3,   2.7,   3. ,   2.9,   3. ,   3. ,   2.5,   2.9,
         2.5,   3.6,   3.2,   2.7,   3. ,   2.5,   2.8,   3.2,   3. ,
         3.8,   2.6,   2.2,   3.2,   2.8,   2.8,   2.7,   3.3,   3.2,
         2.8,   3. ,

In [484]:
con = (Iris > 5) | (Iris < 2) # outlier

In [485]:
sepal_width = np.where(con,3,Iris)
sepal_width

array([3.5, 3. , 3.2, 3.1, 3.6, 3. , 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
       3. , 4. , 4.4, 3. , 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       3. , 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.1, 3. ,
       3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
       3. , 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 3. , 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 3. , 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3.8, 2.8, 2.8, 2.6, 3. , 3.4, 3. , 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. , 2.8, 2.8, 2.7, 3.3, 3.2, 2.5,
       2.9, 2.5, 3. , 2.8, 2.8, 2.7, 3.6, 3.2, 2.7])

In [486]:
sepal_width = np.array(sepal_width,dtype = "float16")
sepal_width

array([3.5, 3. , 3.2, 3.1, 3.6, 3. , 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
       3. , 4. , 4.4, 3. , 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       3. , 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.1, 3. ,
       3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
       3. , 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 3. , 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 3. , 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3.8, 2.8, 2.8, 2.6, 3. , 3.4, 3. , 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. , 2.8, 2.8, 2.7, 3.3, 3.2, 2.5,
       2.9, 2.5, 3. , 2.8, 2.8, 2.7, 3.6, 3.2, 2.7], dtype=float16)

### sepal length

In [474]:
length = Iris[1:,0]
length

array([  5.1,   4.9,   4.7,   4.6,  50. ,   5.4,   4.6,   5. ,   4.4,
         4.9,   5.4,   4.8,   4.8,   4.3,   5.8,   5.7,  50.4,   5.1,
         5.7,   5.1,   5.4,   5.1,   4.6,   5.1,   4.8,   5. ,   5. ,
         5.2,   5.2,   4.7,   4.8,   5.4,   5.2,   5.5,   4.9,   5. ,
         5.5,   4.9,   4.4,   5.1,   5. ,   4.5,   4.4,   5. ,   5.1,
         4.8,   5.1,   4.6,   5.3,   5. ,   7. ,   6.4,   6.9,   5.5,
         6.5,   5.7, 116.3,   4.9,   6.6,   5.2,   5. ,   5.9,   6. ,
         6.1,   5.6,   6.7,   5.6,   5.8,   6.2,   5.6,   5.9,   6.1,
         6.3,   6.1,   6.4,   6.6,   6.8,   6.7,   6. ,   5.7,   5.5,
         5.5,   5.8,   6. ,   5.4,   6. ,   6.7,   6.3,   5.6,   5.5,
         5.5,   6.1,   5.8,   5. ,   5.6,   5.7,   5.7,   6.2,   5.1,
         5.7,   6.3,   5.8,   7.1,   6.3,   6.5,   7.6,   4.9,   7.3,
         6.7,   7.2,   6.5,   6.4,   6.8,   5.7,   5.8,   6.4,   6.5,
         7.7,   7.7,   6. ,   6.9,   5.6,   7.7,   6.3,   6.7,   7.2,
         6.2,   6.1,

In [475]:
np.nanmedian(length)

5.8

In [476]:
a = np.where(np.isnan(length),np.nanmedian(length),length)  # replace nan with nanmedian
a

array([  5.1,   4.9,   4.7,   4.6,  50. ,   5.4,   4.6,   5. ,   4.4,
         4.9,   5.4,   4.8,   4.8,   4.3,   5.8,   5.7,  50.4,   5.1,
         5.7,   5.1,   5.4,   5.1,   4.6,   5.1,   4.8,   5. ,   5. ,
         5.2,   5.2,   4.7,   4.8,   5.4,   5.2,   5.5,   4.9,   5. ,
         5.5,   4.9,   4.4,   5.1,   5. ,   4.5,   4.4,   5. ,   5.1,
         4.8,   5.1,   4.6,   5.3,   5. ,   7. ,   6.4,   6.9,   5.5,
         6.5,   5.7, 116.3,   4.9,   6.6,   5.2,   5. ,   5.9,   6. ,
         6.1,   5.6,   6.7,   5.6,   5.8,   6.2,   5.6,   5.9,   6.1,
         6.3,   6.1,   6.4,   6.6,   6.8,   6.7,   6. ,   5.7,   5.5,
         5.5,   5.8,   6. ,   5.4,   6. ,   6.7,   6.3,   5.6,   5.5,
         5.5,   6.1,   5.8,   5. ,   5.6,   5.7,   5.7,   6.2,   5.1,
         5.7,   6.3,   5.8,   7.1,   6.3,   6.5,   7.6,   4.9,   7.3,
         6.7,   7.2,   6.5,   6.4,   6.8,   5.7,   5.8,   6.4,   6.5,
         7.7,   7.7,   6. ,   6.9,   5.6,   7.7,   6.3,   6.7,   7.2,
         6.2,   6.1,

In [477]:
con = a > 8  # outlier

In [478]:
sepallength = np.where(con,5,a)
sepallength

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5. , 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 5. , 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 5. ,
       5.8, 5.8, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9, 5.6, 7.7, 5.8, 5.8, 7.2, 4.9,
       7.3, 6.7, 5.9, 5.6, 7.7, 6.3, 7.2, 6.5, 6.4])

In [479]:
sepal_length = np.array(sepallength,dtype = "float16")
sepal_length

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5. , 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 5. , 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 5. ,
       5.8, 5.8, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9, 5.6, 7.7, 5.8, 5.8, 7.2, 4.9,
       7.3, 6.7, 5.9, 5.6, 7.7, 6.3, 7.2, 6.5, 6.4], dtype=float16)

### patel length

In [533]:
patellength = Iris[1:,2]
patellength

array([ 1.4,  1.4,  1.3,  1.5,  1.4,  1.7,  1.4,  1.5,  1.4,  nan,  1.5,
        1.6,  1.4,  1.1,  1.2,  1.5,  1.3,  1.4,  1.7,  1.5,  1.7,  1.5,
        1. ,  1.7,  1.9,  1.6,  1.6,  1.5,  1.4,  1.6,  1.6,  1.5,  1.5,
        1.4,  1.5,  1.2,  1.3,  1.5,  1.3,  1.5,  1.3, 13. ,  1.3,  1.6,
        1.9,  1.4,  1.6,  1.4,  1.5,  1.4,  4.7,  4.5,  4.9,  4. ,  4.6,
        4.5,  4.7,  3.3,  4.6,  3.9,  3.5,  4.2,  4. ,  4.7,  3.6,  4.4,
        4.5,  4.1,  4.5,  3.9,  4.8,  4. ,  4.9,  4.7,  4.3,  4.4,  4.8,
        5. ,  4.5,  3.5, 13.8,  3.7,  3.9,  5.1,  4.5,  4.5,  4.7,  4.4,
        4.1,  4. ,  4.4,  nan,  4. ,  3.3,  4.2,  4.2,  4.2,  4.3,  3. ,
        4.1,  6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  4.5,  6.3,  5.8,  6.1,
        5.1,  5.3,  nan,  5. ,  5.1,  5.3,  5.5,  6.7,  6.9,  5. ,  5.7,
        4.9,  6.7,  4.9,  5.7,  6. ,  4.8,  4.9,  5.6,  5.8,  6.1,  nan,
        5.6,  5.1,  5.6,  6.1,  5.6,  5.5,  4.8,  5.4,  nan,  5.1,  5.1,
        5.9,  5.7,  nan,  5. ,  5.2,  5.4,  5.1,  4

In [534]:
np.nanmedian(patellength)

4.5

In [535]:
a = np.where(np.isnan(patellength),np.nanmedian(patellength),patellength) # replace missing value with nanmedian
a

array([ 1.4,  1.4,  1.3,  1.5,  1.4,  1.7,  1.4,  1.5,  1.4,  4.5,  1.5,
        1.6,  1.4,  1.1,  1.2,  1.5,  1.3,  1.4,  1.7,  1.5,  1.7,  1.5,
        1. ,  1.7,  1.9,  1.6,  1.6,  1.5,  1.4,  1.6,  1.6,  1.5,  1.5,
        1.4,  1.5,  1.2,  1.3,  1.5,  1.3,  1.5,  1.3, 13. ,  1.3,  1.6,
        1.9,  1.4,  1.6,  1.4,  1.5,  1.4,  4.7,  4.5,  4.9,  4. ,  4.6,
        4.5,  4.7,  3.3,  4.6,  3.9,  3.5,  4.2,  4. ,  4.7,  3.6,  4.4,
        4.5,  4.1,  4.5,  3.9,  4.8,  4. ,  4.9,  4.7,  4.3,  4.4,  4.8,
        5. ,  4.5,  3.5, 13.8,  3.7,  3.9,  5.1,  4.5,  4.5,  4.7,  4.4,
        4.1,  4. ,  4.4,  4.5,  4. ,  3.3,  4.2,  4.2,  4.2,  4.3,  3. ,
        4.1,  6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  4.5,  6.3,  5.8,  6.1,
        5.1,  5.3,  4.5,  5. ,  5.1,  5.3,  5.5,  6.7,  6.9,  5. ,  5.7,
        4.9,  6.7,  4.9,  5.7,  6. ,  4.8,  4.9,  5.6,  5.8,  6.1,  4.5,
        5.6,  5.1,  5.6,  6.1,  5.6,  5.5,  4.8,  5.4,  4.5,  5.1,  5.1,
        5.9,  5.7,  4.5,  5. ,  5.2,  5.4,  5.1,  4

In [536]:
cond = (a < 1) | (a > 7)  # outlier

In [537]:
patel_length = np.where(cond,4,a)
patel_length

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 4.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3,
       1.5, 1.3, 4. , 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 4. , 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.5, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 4.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 4.5, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 4.5, 5.1, 5.1,
       5.9, 5.7, 4.5, 5. , 5.2, 5.4, 5.1, 4.9, 6.7, 4.9, 5.7, 6. , 4.5,
       6.3, 5.8, 5.1, 4.9, 6.7, 4.9, 6.1, 5.1, 5.3])

In [549]:
patellengthh = np.array(patel_length,dtype = "float16")
patellengthh

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 4.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3,
       1.5, 1.3, 4. , 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 4. , 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.5, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 4.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 4.5, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 4.5, 5.1, 5.1,
       5.9, 5.7, 4.5, 5. , 5.2, 5.4, 5.1, 4.9, 6.7, 4.9, 5.7, 6. , 4.5,
       6.3, 5.8, 5.1, 4.9, 6.7, 4.9, 6.1, 5.1, 5.3], dtype=float16)

### patel width

In [526]:
patel_width = Iris[1:,3]
patel_width

array([2.000e-01, 2.000e-01, 2.000e-01, 1.020e+01, 2.000e-01, 4.000e-01,
       3.000e-01, 2.000e-01, 2.000e-01, 1.000e-01, 2.000e-01, 2.000e-01,
       1.010e+01, 1.000e-01, 2.000e-01, 4.000e-01, 4.000e-01, 3.000e-01,
       3.000e-01, 3.000e-01, 2.000e-01, 4.000e-01, 2.000e-01, 5.000e-01,
       2.000e-01, 2.000e-01, 4.000e-01, 2.000e-01, 1.102e+02, 2.000e-01,
       2.000e-01, 4.000e-01, 1.000e-01, 2.000e-01, 1.000e-01, 2.000e-01,
       2.000e-01, 1.000e-01, 2.000e-01, 2.000e-01, 3.000e-01, 3.000e-01,
       2.000e-01, 6.000e-01, 4.000e-01, 3.000e-01, 2.000e-01, 2.000e-01,
       2.000e-01, 2.000e-01, 1.400e+00, 1.500e+00, 1.500e+00, 1.300e+00,
       1.500e+00, 1.300e+00, 1.600e+00, 1.600e+01, 1.300e+00, 1.400e+00,
       1.000e+00, 1.500e+00, 1.000e+00, 1.400e+00, 1.300e+00, 1.400e+00,
       1.500e+00, 1.000e+00, 1.500e+00, 1.100e+00, 1.800e+00, 1.300e+00,
       1.500e+00, 1.200e+00, 1.300e+00, 1.400e+00, 1.400e+00, 1.700e+00,
       1.500e+00, 1.000e+00, 1.100e+00, 1.000e+00, 

In [527]:
np.nanmedian(patel_width)

1.5

In [528]:
a = np.where(np.isnan(patel_width),np.nanmedian(patel_width),patel_width) # replace missing value with nanmedian
a

array([2.000e-01, 2.000e-01, 2.000e-01, 1.020e+01, 2.000e-01, 4.000e-01,
       3.000e-01, 2.000e-01, 2.000e-01, 1.000e-01, 2.000e-01, 2.000e-01,
       1.010e+01, 1.000e-01, 2.000e-01, 4.000e-01, 4.000e-01, 3.000e-01,
       3.000e-01, 3.000e-01, 2.000e-01, 4.000e-01, 2.000e-01, 5.000e-01,
       2.000e-01, 2.000e-01, 4.000e-01, 2.000e-01, 1.102e+02, 2.000e-01,
       2.000e-01, 4.000e-01, 1.000e-01, 2.000e-01, 1.000e-01, 2.000e-01,
       2.000e-01, 1.000e-01, 2.000e-01, 2.000e-01, 3.000e-01, 3.000e-01,
       2.000e-01, 6.000e-01, 4.000e-01, 3.000e-01, 2.000e-01, 2.000e-01,
       2.000e-01, 2.000e-01, 1.400e+00, 1.500e+00, 1.500e+00, 1.300e+00,
       1.500e+00, 1.300e+00, 1.600e+00, 1.600e+01, 1.300e+00, 1.400e+00,
       1.000e+00, 1.500e+00, 1.000e+00, 1.400e+00, 1.300e+00, 1.400e+00,
       1.500e+00, 1.000e+00, 1.500e+00, 1.100e+00, 1.800e+00, 1.300e+00,
       1.500e+00, 1.200e+00, 1.300e+00, 1.400e+00, 1.400e+00, 1.700e+00,
       1.500e+00, 1.000e+00, 1.100e+00, 1.000e+00, 

In [529]:
con = a > 11  # outlier

In [530]:
patelwidth = np.where(con,2,a)
patelwidth

array([ 0.2,  0.2,  0.2, 10.2,  0.2,  0.4,  0.3,  0.2,  0.2,  0.1,  0.2,
        0.2, 10.1,  0.1,  0.2,  0.4,  0.4,  0.3,  0.3,  0.3,  0.2,  0.4,
        0.2,  0.5,  0.2,  0.2,  0.4,  0.2,  2. ,  0.2,  0.2,  0.4,  0.1,
        0.2,  0.1,  0.2,  0.2,  0.1,  0.2,  0.2,  0.3,  0.3,  0.2,  0.6,
        0.4,  0.3,  0.2,  0.2,  0.2,  0.2,  1.4,  1.5,  1.5,  1.3,  1.5,
        1.3,  1.6,  2. ,  1.3,  1.4,  1. ,  1.5,  1. ,  1.4,  1.3,  1.4,
        1.5,  1. ,  1.5,  1.1,  1.8,  1.3,  1.5,  1.2,  1.3,  1.4,  1.4,
        1.7,  1.5,  1. ,  1.1,  1. ,  1.2,  1.6,  1.5,  1.6,  1.5,  1.3,
        1.3,  1.3,  1.2,  1.4,  1.2,  1. ,  1.3,  1.2,  1.3,  1.3,  2. ,
        1.3,  2.5,  1.9,  2.1,  1.8,  2.2,  2.1,  1.7,  1.8,  1.8,  2.5,
        2. ,  1.9,  2.1,  2. ,  2.4,  2.3,  1.8,  2.2,  2.3,  1.5,  2.3,
        2. ,  2. ,  1.8,  2.1,  1.8,  1.8,  1.8,  2.1,  1.6,  1.9,  2. ,
        2.2,  1.5,  1.4,  2.3,  2.4,  1.8,  1.8,  2.1,  2.4,  2.3,  1.9,
        2.3,  2.5,  2.3,  1.9,  2. ,  2.3,  1.8,  2

In [550]:
patelwidthh = np.array(patelwidth,dtype = "float16")
patelwidthh

array([ 0.2,  0.2,  0.2, 10.2,  0.2,  0.4,  0.3,  0.2,  0.2,  0.1,  0.2,
        0.2, 10.1,  0.1,  0.2,  0.4,  0.4,  0.3,  0.3,  0.3,  0.2,  0.4,
        0.2,  0.5,  0.2,  0.2,  0.4,  0.2,  2. ,  0.2,  0.2,  0.4,  0.1,
        0.2,  0.1,  0.2,  0.2,  0.1,  0.2,  0.2,  0.3,  0.3,  0.2,  0.6,
        0.4,  0.3,  0.2,  0.2,  0.2,  0.2,  1.4,  1.5,  1.5,  1.3,  1.5,
        1.3,  1.6,  2. ,  1.3,  1.4,  1. ,  1.5,  1. ,  1.4,  1.3,  1.4,
        1.5,  1. ,  1.5,  1.1,  1.8,  1.3,  1.5,  1.2,  1.3,  1.4,  1.4,
        1.7,  1.5,  1. ,  1.1,  1. ,  1.2,  1.6,  1.5,  1.6,  1.5,  1.3,
        1.3,  1.3,  1.2,  1.4,  1.2,  1. ,  1.3,  1.2,  1.3,  1.3,  2. ,
        1.3,  2.5,  1.9,  2.1,  1.8,  2.2,  2.1,  1.7,  1.8,  1.8,  2.5,
        2. ,  1.9,  2.1,  2. ,  2.4,  2.3,  1.8,  2.2,  2.3,  1.5,  2.3,
        2. ,  2. ,  1.8,  2.1,  1.8,  1.8,  1.8,  2.1,  1.6,  1.9,  2. ,
        2.2,  1.5,  1.4,  2.3,  2.4,  1.8,  1.8,  2.1,  2.4,  2.3,  1.9,
        2.3,  2.5,  2.3,  1.9,  2. ,  2.3,  1.8,  2

### 2.what is the mean value of sepal length

In [463]:
sepal_length = np.mean(sepallength)  # mean
sepal_length

5.851515151515152

### 3.sort the sepal width in ascending order

In [253]:
sepal_width = np.sort(sepal_width) #sort
sepal_width

array([2. , 2.2, 2.2, 2.2, 2.3, 2.3, 2.3, 2.3, 2.4, 2.4, 2.4, 2.5, 2.5,
       2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.6, 2.6, 2.6, 2.6, 2.7,
       2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.8, 2.8,
       2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8,
       2.8, 2.8, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3.1, 3.1, 3.1, 3.1, 3.1,
       3.1, 3.1, 3.1, 3.1, 3.1, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2,
       3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3,
       3.3, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.5,
       3.5, 3.5, 3.5, 3.5, 3.5, 3.6, 3.6, 3.6, 3.6, 3.7, 3.7, 3.7, 3.8,
       3.8, 3.8, 3.8, 3.8, 3.8, 4. , 4.1, 4.2, 4.4], dtype=float16)

### 4.apply all statistical measures on sepal with and length

### sepal width

In [254]:
np.mean(sepal_width) # mean

3.03

In [255]:
np.median(sepal_width) # median

3.0

In [256]:
np.var(sepal_width) #variance

0.1683

In [257]:
np.std(sepal_width) #standard deviation

0.4104

In [258]:
Range = np.max(sepal_width)-np.min(sepal_width) # range
Range

2.398

In [259]:
Q3 = np.percentile(sepal_width,75)  #IQR
Q1 = np.percentile(sepal_width,25)
IQR = Q3 - Q1
IQR

0.3984375

### sepal length

In [260]:
np.mean(sepallength)  # mean

5.851515151515152

In [261]:
np.median(sepallength) #median

5.8

In [262]:
np.var(sepallength) # variance

0.6714674012855831

In [263]:
np.std(sepallength) #standard deviation

0.8194311449326191

In [264]:
Range = np.max(sepallength) - np.min(sepallength) # range
Range

3.4000000000000004

In [195]:
Q3 = np.percentile(b,75)  # IQR
Q1 = np.percentile(b,25)
IQR = Q3 - Q1
IQR

1.3000000000000007

### 5.after cleaning the data save the file as "cleaned_Iris.txt" and load to jupter again

In [543]:
sepal = np.hstack((sepal_length,sepal_width))
sepal

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5. , 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 5. , 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 5. ,
       5.8, 5.8, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9, 5.6, 7.7, 5.8, 5.8, 7.2, 4.9,
       7.3, 6.7, 5.9, 5.6, 7.7, 6.3, 7.2, 6.5, 6.4, 3.5, 3. , 3.2, 3.1,
       3.6, 3. , 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. , 3. , 4. , 4.

In [551]:
patel = np.hstack((patellengthh,patelwidthh))
patel

array([ 1.4,  1.4,  1.3,  1.5,  1.4,  1.7,  1.4,  1.5,  1.4,  4.5,  1.5,
        1.6,  1.4,  1.1,  1.2,  1.5,  1.3,  1.4,  1.7,  1.5,  1.7,  1.5,
        1. ,  1.7,  1.9,  1.6,  1.6,  1.5,  1.4,  1.6,  1.6,  1.5,  1.5,
        1.4,  1.5,  1.2,  1.3,  1.5,  1.3,  1.5,  1.3,  4. ,  1.3,  1.6,
        1.9,  1.4,  1.6,  1.4,  1.5,  1.4,  4.7,  4.5,  4.9,  4. ,  4.6,
        4.5,  4.7,  3.3,  4.6,  3.9,  3.5,  4.2,  4. ,  4.7,  3.6,  4.4,
        4.5,  4.1,  4.5,  3.9,  4.8,  4. ,  4.9,  4.7,  4.3,  4.4,  4.8,
        5. ,  4.5,  3.5,  4. ,  3.7,  3.9,  5.1,  4.5,  4.5,  4.7,  4.4,
        4.1,  4. ,  4.4,  4.5,  4. ,  3.3,  4.2,  4.2,  4.2,  4.3,  3. ,
        4.1,  6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  4.5,  6.3,  5.8,  6.1,
        5.1,  5.3,  4.5,  5. ,  5.1,  5.3,  5.5,  6.7,  6.9,  5. ,  5.7,
        4.9,  6.7,  4.9,  5.7,  6. ,  4.8,  4.9,  5.6,  5.8,  6.1,  4.5,
        5.6,  5.1,  5.6,  6.1,  5.6,  5.5,  4.8,  5.4,  4.5,  5.1,  5.1,
        5.9,  5.7,  4.5,  5. ,  5.2,  5.4,  5.1,  4

In [555]:
iris = np.hstack((sepal,patel))
iris

array([ 5.1,  4.9,  4.7,  4.6,  5. ,  5.4,  4.6,  5. ,  4.4,  4.9,  5.4,
        4.8,  4.8,  4.3,  5.8,  5.7,  5. ,  5.1,  5.7,  5.1,  5.4,  5.1,
        4.6,  5.1,  4.8,  5. ,  5. ,  5.2,  5.2,  4.7,  4.8,  5.4,  5.2,
        5.5,  4.9,  5. ,  5.5,  4.9,  4.4,  5.1,  5. ,  4.5,  4.4,  5. ,
        5.1,  4.8,  5.1,  4.6,  5.3,  5. ,  7. ,  6.4,  6.9,  5.5,  6.5,
        5.7,  5. ,  4.9,  6.6,  5.2,  5. ,  5.9,  6. ,  6.1,  5.6,  6.7,
        5.6,  5.8,  6.2,  5.6,  5.9,  6.1,  6.3,  6.1,  6.4,  6.6,  6.8,
        6.7,  6. ,  5.7,  5.5,  5.5,  5.8,  6. ,  5.4,  6. ,  6.7,  6.3,
        5.6,  5.5,  5.5,  6.1,  5.8,  5. ,  5.6,  5.7,  5.7,  6.2,  5.1,
        5.7,  6.3,  5.8,  7.1,  6.3,  6.5,  7.6,  4.9,  7.3,  6.7,  7.2,
        6.5,  6.4,  6.8,  5.7,  5.8,  6.4,  6.5,  7.7,  7.7,  6. ,  6.9,
        5.6,  7.7,  6.3,  6.7,  7.2,  6.2,  6.1,  6.4,  5. ,  5.8,  5.8,
        6.4,  6.3,  6.1,  7.7,  6.3,  6.4,  6. ,  6.9,  6.7,  6.9,  5.8,
        6.8,  6.7,  6.7,  6.3,  6.5,  6.2,  5.9,  5

In [556]:
np.savetxt('cleaned_iris.txt',iris)

In [557]:
np.loadtxt('cleaned_iris.txt')

array([ 5.1015625 ,  4.8984375 ,  4.69921875,  4.6015625 ,  5.        ,
        5.3984375 ,  4.6015625 ,  5.        ,  4.3984375 ,  4.8984375 ,
        5.3984375 ,  4.80078125,  4.80078125,  4.30078125,  5.80078125,
        5.69921875,  5.        ,  5.1015625 ,  5.69921875,  5.1015625 ,
        5.3984375 ,  5.1015625 ,  4.6015625 ,  5.1015625 ,  4.80078125,
        5.        ,  5.        ,  5.19921875,  5.19921875,  4.69921875,
        4.80078125,  5.3984375 ,  5.19921875,  5.5       ,  4.8984375 ,
        5.        ,  5.5       ,  4.8984375 ,  4.3984375 ,  5.1015625 ,
        5.        ,  4.5       ,  4.3984375 ,  5.        ,  5.1015625 ,
        4.80078125,  5.1015625 ,  4.6015625 ,  5.30078125,  5.        ,
        7.        ,  6.3984375 ,  6.8984375 ,  5.5       ,  6.5       ,
        5.69921875,  5.        ,  4.8984375 ,  6.6015625 ,  5.19921875,
        5.        ,  5.8984375 ,  6.        ,  6.1015625 ,  5.6015625 ,
        6.69921875,  5.6015625 ,  5.80078125,  6.19921875,  5.60