### Creation of ndarray

#### 1.Write python code to create 3d array in different ways with 15 elements.

In [1]:
import numpy as np

In [4]:
arr = np.array([10,15,20,25,30,35,40,45,50,55,60,65,70,75,80],ndmin = 3) #method-1
arr

array([[[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80]]])

In [9]:
arr = np.array([10,15,20,25,30,35,40,45,50,55,60,65,70,75,80]).reshape(5,1,3) #method-2
arr

array([[[10, 15, 20]],

       [[25, 30, 35]],

       [[40, 45, 50]],

       [[55, 60, 65]],

       [[70, 75, 80]]])

In [10]:
arr = np.array([[[10,15,20,25,30,35,40,45,50,55,60,65,70,75,80]]]) #method-3
arr

array([[[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80]]])

#### 2.Array Creation:

##### a. Create a 4D NumPy array containing the first 12 positive integers as arr1

In [23]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12],ndmin = 4)
arr1

array([[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]]])

#### b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1

In [34]:
arr2 = np.random.randint(0,2,20).reshape(5,1,4)
arr2

array([[[1, 1, 0, 0]],

       [[1, 1, 1, 1]],

       [[1, 0, 0, 0]],

       [[1, 1, 0, 0]],

       [[0, 0, 1, 1]]])

####  3. Find all attributes of array1 and array2

##### attributes of arr1

In [35]:
arr1

array([[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]]])

In [37]:
arr1.dtype  # data type

dtype('int32')

In [38]:
arr1.size # no.of elements in array

12

In [39]:
arr1.nbytes # memory size of array

48

In [40]:
arr1.itemsize #memory occupied by each item

4

In [42]:
arr1.ndim # dimension

4

##### attributes of arr2

In [43]:
arr2

array([[[1, 1, 0, 0]],

       [[1, 1, 1, 1]],

       [[1, 0, 0, 0]],

       [[1, 1, 0, 0]],

       [[0, 0, 1, 1]]])

In [44]:
arr2.dtype # data type

dtype('int32')

In [45]:
arr2.size # no.of elements

20

In [46]:
arr2.nbytes # memory occupied by array

80

In [47]:
arr2.itemsize # memory occupied by each item

4

In [49]:
arr2.ndim # dimension

3

#### 4.Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.

##### descriptive statistics of arr1

In [50]:
arr1

array([[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]]])

In [51]:
np.mean(arr1) # mean

6.5

In [52]:
np.median(arr1) # middle most value

6.5

In [53]:
np.var(arr1) # variance

11.916666666666666

In [54]:
np.std(arr1) # standard deviation

3.452052529534663

In [55]:
Range = np.max(arr1) - np.min(arr1) # Range
Range

11

In [61]:
Q3 = np.percentile(arr1,75) #IQR
Q1 = np.percentile(arr1,25)
IQR = Q3 - Q1
IQR

5.5

In [64]:
lower_limit = Q1-1.5*IQR
print(lower_limit)
upper_limit = Q3+1.5*IQR
print(upper_limit)

-4.5
17.5


In [67]:
print(arr1[arr1 < lower_limit]) # outlier-no outlier in arr1
print(arr1[arr1 > upper_limit])

[]
[]


##### descriptive statistics of arr2

In [68]:
arr2

array([[[1, 1, 0, 0]],

       [[1, 1, 1, 1]],

       [[1, 0, 0, 0]],

       [[1, 1, 0, 0]],

       [[0, 0, 1, 1]]])

In [71]:
np.mean(arr2) # mean

0.55

In [72]:
np.median(arr2) # median

1.0

In [73]:
np.var(arr2) # variance

0.24749999999999997

In [74]:
np.std(arr2) # standard deviation

0.4974937185533099

In [75]:
Range = np.max(arr2) - np.min(arr2)  # Range = max-min
Range

1

In [76]:
Q3 = np.percentile(arr2,75) #IQR
Q1 = np.percentile(arr2,25)
IQR = Q3 - Q1
IQR

1.0

In [78]:
lower_limit = Q1-1.5*IQR
print(lower_limit)
upper_limit = Q3+1.5*IQR
print(upper_limit)
print(arr2[arr2 < lower_limit]) # outlier-no outlier in arr1
print(arr2[arr2 > upper_limit])

-1.5
2.5
[]
[]


### Array Slicing and Indexing:

#### a. Creating Arrays: - Create a 1-dimensional NumPy array arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29]. 

In [81]:
arr1 = np.array([0, 11, 26, 73, 42, 51, 6,77, 8,29]) # 1-d
arr1

array([ 0, 11, 26, 73, 42, 51,  6, 77,  8, 29])

####  - Create a 2-dimensional NumPy array arr2 with the values [[0, 1, 2], [3, 4, 5], [6, 7, 8]].¶

In [82]:
arr2 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]]) # 2-d
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### b.Basic Indexing: - Print the element at index 3 of arr1. 

In [83]:
arr1[3] # arr1

73

#### - Print the element at row 2, column 1 of arr2

In [85]:
print(arr2[2,1])  # arr2
print(arr2[2][1])

7
7


#### c. Array Slicing: - Print the first five elements of arr1. 

In [87]:
arr1[0:5]  # arr1

array([ 0, 11, 26, 73, 42])

#### - Print the subarray of arr2 consisting of the last two rows and the first two columns

In [93]:
arr2[1:3,0:2] # sub array of arr2

array([[3, 4],
       [6, 7]])

#### print every second element starting from index 1 up to index 7 of arr1

In [95]:
arr1[1:7:2]  

array([11, 73, 51])

### Data Type Manipulation

#### a. Creating Arrays with Specific Data Types:4

#### - Create a 1-dimensional NumPy array int_array with the values [1, 2, 3, 4, 5] and the data type int16. 

In [101]:
arr1 = np.array([1, 2, 3, 4, 5],dtype = 'int16')
arr1

array([1, 2, 3, 4, 5], dtype=int16)

#### Create a 1-dimensional NumPy array float_array with the values [0.1, 0.2, 0.3, 0.4, 0.5] and the data type float64.


In [102]:
arr2 = np.array([0.1, 0.2, 0.3, 0.4, 0.5],dtype = "float64")
arr2

array([0.1, 0.2, 0.3, 0.4, 0.5])

#### b. Data Type Conversion:

#### : - Convert the float_array to an array with data type int32.

In [105]:
arr2 = np.array([0.1, 0.2, 0.3, 0.4, 0.5],dtype = "int32")
arr2

array([0, 0, 0, 0, 0])

####  Print the result. - Convert the int_array to an array with data type float32. Print the result¶

In [106]:
arr1 = np.array([1, 2, 3, 4, 5],dtype = 'float32')
arr1

array([1., 2., 3., 4., 5.], dtype=float32)

### Generating Random Numbers:

#### 1.Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

In [109]:
import numpy
arr = numpy.random.randint(0,101,10)
arr

array([26, 15,  7, 78, 47, 81, 11, 45, 12, 17])

#### 2.Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

In [111]:
arr = numpy.random.uniform(-1,1,5)
arr

array([ 0.51272506,  0.40189395, -0.69103009,  0.19032041, -0.20815777])

#### 3.Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

In [122]:
arr = numpy.random.randint(50,100,16).reshape(4,4)
arr

array([[57, 55, 86, 66],
       [81, 57, 73, 71],
       [93, 84, 88, 92],
       [81, 93, 57, 98]])

#### 4.Apply descriptive statistics for rand_matrix.

In [124]:
np.mean(arr)  # mean

77.0

In [126]:
np.median(arr) # median

81.0

In [127]:
np.var(arr)  # variance

207.375

In [128]:
np.std(arr)  # standard deviation

14.400520823914668

In [130]:
Range = np.max(arr) - np.min(arr) # range
Range

43

In [131]:
Q3 = np.percentile(arr,75) #IQR
Q1 = np.percentile(arr,25)
IQR = Q3 - Q1
IQR

25.25

In [132]:
lower_limit = Q1-1.5*IQR
print(lower_limit)
upper_limit = Q3+1.5*IQR
print(upper_limit)
print(arr[arr < lower_limit]) # outlier-no outlier in arr1
print(arr[arr > upper_limit])

25.875
126.875
[]
[]


### Analyze the Data:

#### Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]



In [133]:
Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

In [141]:
arr = np.array(Salaries)
arr

array([  87877,   54494,   54804,   85051,   52453,   31250,   94868,
         66349,   39828,   60501,   58570,   74906,   41671,   51428,
         56414,   98446,   56819,   82833,   50477,   62898,   99658,
         89224,   34225,   79172,   32199,   63795,   90947,   55723,
         64557, 3113638])

#### Describe the data using numpy array. Measure the following:

#### 1.How many employees are getting more less than 50000

In [147]:
len(arr[arr < 50000])

5

#### 2.Is it following Normal Distribution?

In [ ]:
No  # because data is not normally distributed it has extreme high value 3113638(outlier)

#### 3.What is the median salary?

In [148]:
np.median(arr)

61699.5

#### 4.What is the range of salaries for this company?

In [149]:
Range = np.max(arr) - np.min(arr)
Range

3082388

#### 5.Find the salaries between average salary and 75% of salaries?

In [166]:
a = np.mean(arr)
print(a)

Q3 = np.percentile(arr,75)
print(Q3)

print(arr[(arr > Q3) & (arr < a)])

166169.16666666666
84496.5
[87877 85051 94868 98446 99658 89224 90947]


#### 6.How many employees are getting less than 25 % of salaries ?

In [171]:
Q1 = np.percentile(arr,25)
print(Q1)

print(arr[arr < Q1])

print(len(arr[arr < Q1]))

52963.25
[52453 31250 39828 41671 51428 50477 34225 32199]
8
