### 1.write python code to create array in different ways

In [2]:
import numpy as np

In [3]:
# method 1

arr = np.array([20,30,40,50,60])
arr

array([20, 30, 40, 50, 60])

In [8]:
# method 2 using tuple

arr = np.array((1,2,3,4,5))
arr

array([1, 2, 3, 4, 5])

In [4]:
# method -  np.zeros()-array filled with all zeros

arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [5]:
# method - np.ones()-array filled with all ones

arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [6]:
# method - np.arange()-array filled with regularly spaced values


arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# method - np.linspace()-array filled with evenly spaced values

arr = np.linspace(1,10,4)
arr

array([ 1.,  4.,  7., 10.])

### 2.array creation

#### a.create a 1D Numpy array containing the first 12 positive integer as arr1

In [96]:
arr1 = np.arange(1,13)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [97]:
len(arr1)

12

In [98]:
id(arr1)

2213534919792

In [99]:
type(arr1)

numpy.ndarray

#### b.create a 1D Numpy array1 with 20 elements containing  integer between 0 and 12 using linspace

In [100]:
arr2 = np.linspace(1,12,20)
arr2

array([ 1.        ,  1.57894737,  2.15789474,  2.73684211,  3.31578947,
        3.89473684,  4.47368421,  5.05263158,  5.63157895,  6.21052632,
        6.78947368,  7.36842105,  7.94736842,  8.52631579,  9.10526316,
        9.68421053, 10.26315789, 10.84210526, 11.42105263, 12.        ])

In [101]:
len(arr2)

20

In [102]:
type(arr2)

numpy.ndarray

In [103]:
id(arr2)

2213534920752

### 3.find all attributes of arr1 and arr2

#### arr1

In [11]:
arr1.dtype  # dtype-data type of array

dtype('int32')

In [14]:
arr1.size  # size-no.of elements

12

In [15]:
arr1.nbytes  #nbytes-memory occupied by array

48

In [16]:
arr1.itemsize #itemsize-memory occupied by each item

4

#### arr2

In [17]:
arr2.dtype  # dtype-data type of array

dtype('float64')

In [18]:
arr2.size  # size-no.of elements

20

In [19]:
arr2.nbytes #nbytes-memory occupied by array

160

In [20]:
arr2.itemsize #itemsize-memory occupied by each item

8

### 4.apply measure and describe the data(attribue and statistics) to above arrays using Numpy

### arr1

In [59]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [67]:
np.mean(arr1) # mean-avg

6.5

In [24]:
np.median(arr1) # median-middle value

6.5

In [81]:
Range =  max(arr1) - min(arr1) # range-max-min
Range

11

In [82]:
np.var(arr1)  # variance-how data values spread from mean

11.916666666666666

In [83]:
np.std(arr1)  # standard deviation-deviating from mean

3.452052529534663

In [84]:
Q1 = np.percentile(arr1,25)  # IQR = Q3-Q1
Q3 = np.percentile(arr1,75)
IQR = Q3 - Q1
IQR

5.5

In [85]:
lower_limit = Q1 - (1.5)*(IQR)
print("lower_limit:",lower_limit)
upper_limit = Q3 + (1.5)*(IQR)
print("upper_limit:",upper_limit)

lower_limit: -4.5
upper_limit: 17.5


In [86]:
print(arr1[arr1>upper_limit])  # outlier-there is no outliers in arr1
print(arr1[arr1<lower_limit])

[]
[]


### arr2

In [87]:
arr2

array([ 1.        ,  1.57894737,  2.15789474,  2.73684211,  3.31578947,
        3.89473684,  4.47368421,  5.05263158,  5.63157895,  6.21052632,
        6.78947368,  7.36842105,  7.94736842,  8.52631579,  9.10526316,
        9.68421053, 10.26315789, 10.84210526, 11.42105263, 12.        ])

In [88]:
np.mean(arr2)  # mean-avg

6.5

In [89]:
np.median(arr2) # median-middle value

6.5

In [90]:
np.var(arr2)  # var- how data values spread from mean

11.144736842105264

In [91]:
np.std(arr2) # std-deviating from mean

3.338373382667862

In [92]:
Range = max(arr2) - min(arr2) # Range-max-min
Range

11.0

In [93]:
Q3 = np.percentile(arr2,75) 
Q1 = np.percentile(arr2,25)  # Range = max-min
IQR =Q3 - Q1
IQR

5.5

In [94]:
lower_limit = Q1 - (1.5)*(IQR)
print("lower_limit:",lower_limit)
upper_limit = Q3 + (1.5)*(IQR)
print("upper_limit:",upper_limit)

lower_limit: -4.5
upper_limit: 17.5


In [95]:
print(arr1[arr1>upper_limit])  # outlier-there is no outliers in arr2
print(arr1[arr1<lower_limit])

[]
[]
